<?php

/*
 *     __  ___      ____  _ _    __               _
 *    /  |/  /_  __/ / /_(_) |  / /__  __________(_)___  ____
 *   / /|_/ / / / / / __/ /| | / / _ \/ ___/ ___/ / __ \/ __ \
 *  / /  / / /_/ / / /_/ / | |/ /  __/ /  (__  ) / /_/ / / / /
 * /_/  /_/\__,_/_/\__/_/  |___/\___/_/  /____/_/\____/_/ /_/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author JoggingSplash23
 * @link https://www.github.com/JoggingSplash
 *
 *
 */

declare(strict_types=1);

namespace cisco\network\proto\v419\structure;

use cisco\network\utils\ProtocolUtils;
use pocketmine\network\mcpe\protocol\ClientboundPacket;
use pocketmine\network\mcpe\protocol\Packet;
use pocketmine\network\mcpe\protocol\PacketPool;
use pocketmine\network\mcpe\protocol\ServerboundPacket;

class v419PacketPool extends PacketPool
{

	public function __construct()
	{
		parent::__construct();

		// Override packets
		ProtocolUtils::registerPackets($this, v419ProtocolInfo::CURRENT_PROTOCOL);
	}

	/**
	 * @return ServerboundPacket|ClientboundPacket|Packet|null
	 */
	public function getPacketById(int $pid) : ?Packet
	{
		return parent::getPacketById($pid); // TODO: Change the autogenerated stub
	}
}
