<?php

/*
 *     __  ___      ____  _ _    __               _
 *    /  |/  /_  __/ / /_(_) |  / /__  __________(_)___  ____
 *   / /|_/ / / / / / __/ /| | / / _ \/ ___/ ___/ / __ \/ __ \
 *  / /  / / /_/ / / /_/ / | |/ /  __/ /  (__  ) / /_/ / / / /
 * /_/  /_/\__,_/_/\__/_/  |___/\___/_/  /____/_/\____/_/ /_/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author JoggingSplash23
 * @link https://www.github.com/JoggingSplash
 *
 *
 */

declare(strict_types=1);

namespace cisco\network\proto\v419\packets;

use cisco\network\proto\v419\packets\types\recipe\v419RecipeWithTypeId;
use cisco\network\proto\v419\structure\v419ProtocolInfo;
use pmmp\encoding\ByteBufferReader;
use pmmp\encoding\ByteBufferWriter;
use pmmp\encoding\VarInt;
use pocketmine\network\mcpe\protocol\CraftingDataPacket;
use pocketmine\network\mcpe\protocol\serializer\CommonTypes;
use function count;

class v419CraftingDataPacket extends CraftingDataPacket
{
	public const NETWORK_ID = v419ProtocolInfo::CRAFTING_DATA_PACKET;

	/** @var v419RecipeWithTypeId[] */
	public array $_entries = [];

	static public function v419create(array $new_entries) : self
	{
		$npk = new self();
		$npk->_entries = $new_entries;
		return $npk;
	}

	protected function encodePayload(ByteBufferWriter $out) : void
	{
		VarInt::writeUnsignedInt($out, count($this->_entries));
		foreach ($this->_entries as $d) {
			VarInt::writeSignedInt($out, $d->getTypeId());
			$d->write($out);
		}

		VarInt::writeUnsignedInt($out, 0);
		VarInt::writeUnsignedInt($out, 0);
		CommonTypes::putBool($out, $this->cleanRecipes);
	}

	protected function decodePayload(ByteBufferReader $in) : void
	{
		parent::decodePayload($in); // TODO: Change the autogenerated stub
	}
}
